collectd:
  #Executed after config-change
  reload_cmd: 'echo /etc/init.d/collectd_reload'
  
  # Generate Ping-Configuration
  ping:
    template: './lib/collectd/templates/ping.conf.erb'
    path: '/tmp/ping_hosts.conf'

  stats:
    ping: #Configuration for ping-graphs
      dir: '/Users/jan/freifunk/mon_serv/rrd/collecd.kbu.freifunk.net'
      address: '<%= node.link_local %>%eth1.rrd'  
 
    