collectd:
  stats:
    ping: #Configuration for ping-graphs
      dir: '/var/lib/collectd/rrd/collecd.kbu.freifunk.net'
      address: '<%= node.link_local %>%eth1.rrd'  
  reload_cmd: 'sudo /etc/init.d/collectd restart'
  ping:
    template: '/srv/mon_serv/templates/ping.conf.erb'
    path: '/etc/collectd/mesh-conf/ping.conf'
    