collectd:
  reload_cmd: 'sudo /etc/init.d/collectd restart'
  stats:
    ping: #Configuration for ping-graphs
      type: PingStat
      dir: '/home/jan/git/mon_serv/db/rrd/collecd.kbu.freifunk.net'
      address: '<%= node.link_local %>%eth1.rrd'  
    interface: #Configuration for interface-graphs
      type: InterfaceRxTxStat
      dir: '/home/jan/git/mon_serv/db/rrd/<%= node.id_hex %>.nodes.kbu.freifunk.net/interface/'
    error: #Configuration for interface-graphs
      type: InterfaceErrorStat
      dir: '/home/jan/git/mon_serv/db/rrd/<%= node.id_hex %>.nodes.kbu.freifunk.net/interface/'
    iwinfo:
      type: IwinfoStat
      dir: '/home/jan/git/mon_serv/db/rrd/<%= node.id_hex %>.nodes.kbu.freifunk.net/'

  ping:
    template: './templates/ping.conf.erb'
    path: '/etc/collectd/mesh-conf/ping.conf'
    interface: 'eth1'
